### PR TITLE
[BREAKING CHANGE] Replace rtm.start with rtm.connect

### LINKED ISSUE #181: Crash upon start
Hi there! https://github.com/BlakeWilliams/Elixir-Slack/pull/177 introduces a bug that causes the app to crash upon start...

See the https://github.com/BlakeWilliams/Elixir-Slack/pull/177#issuecomment-461811475

```
** (EXIT from #PID<0.323.0>) shell process exited with reason: an exception was raised:
    ** (KeyError) key :bots not found in: %{ok: true, self: %{...}, team: %{...}, url: "..."}
        (slack) lib/slack/bot.ex:90: Slack.Bot.init/1
        (websocket_client) /.../deps/websocket_client/src/websocket_client.erl:164: :websocket_client.init/1
        (stdlib) gen_fsm.erl:351: :gen_fsm.init_it/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

cc/ @acconrad @BlakeWilliams @aquarhead

### PR DESCRIPTION
**Pull request by acconrad**
Replace `rtm.start` with `rtm.connect` and bump to a major version along with a migration guide.

### CODE REVIEW

File: lib/slack/bot.ex [hunk 1]
```diff
@@ -87,11 +87,11 @@ defmodule Slack.Bot do
       token: token,
       me: rtm.self,
       team: rtm.team,
-      bots: rtm_list_to_map(rtm.bots),
-      channels: rtm_list_to_map(rtm.channels),
-      groups: rtm_list_to_map(rtm.groups),
-      users: rtm_list_to_map(rtm.users),
-      ims: rtm_list_to_map(rtm.ims)
+      bots: rtm_list_to_map(Slack.Web.Bots.info(%{token: token}) |> Map.get("bot")),
```
Comment (BlakeWilliams) [inline lib/slack/bot.ex]: This would kick off 5 different requests at once which I don't think is ideal. Is there no equivalent API to `rtm.start` to bootstrap the client?

Comment (BlakeWilliams) [reply lib/slack/bot.ex]: I can't link to it directly, but https://api.slack.com/rtm has `rtm.connect` vs `rtm.start`. It looks like both are still valid.

I'd be okay with reverting the change to use `rtm.connect` meaning the library will continue to only support `rtm.start` until someone takes the time to add `rtm.connect` support (assuming anyone needs it over `rtm.start`).

That being said, it does look like this approach of making multiple requests is how Slack recommends you use `rtm.connect`.

Comment (acconrad) [reply lib/slack/bot.ex]: > That being said, it does look like this approach of making multiple requests is how Slack recommends you use rtm.connect.

That, and anyone using the Enterprise Grid with `rtm.start` will not work as expected if we stick with the old solution

**Comment by BlakeWilliams** [comment]
👋 thanks for tackling this. In terms of tests I've setup a basic fake API. The initial entry-point is here: `https://github.com/BlakeWilliams/Elixir-Slack/blob/master/test/support/fake_slack.ex#L22` which then uses the Router defined here: https://github.com/BlakeWilliams/Elixir-Slack/blob/master/test/support/fake_slack/router.ex

It's a simple Plug based router/app so we could likely extend that to return fake results for each of those API Calls.

File: lib/slack/bot.ex (hunk 1 above)
Comment (BlakeWilliams) [reply lib/slack/bot.ex]: That is true. I'm not super concerned about supporting it but if we want to move forward with this and we get support at the same time I'm all for it 👍

**Comment by acconrad** [comment]
@BlakeWilliams cool I'll check that out tonight.

Another option I considered is having 2 private functions within the `init` call: 

1 that we currently have that supports the current functionality of the 5 requests going in tandem to legacy support `rtm.start`. 

The other function would not have that flag on and would only return the standard `rtm.connect` base objects. That way we can send a deprecation message in the old function saying something like "pulling all objects will be retired in the next version, update accordingly" - and then when you update a major version of this plugin, all you have to do is delete the old function and rely only on the new function.

Does that make sense?

**Comment by BlakeWilliams** [comment]
That makes sense to me. As long as we expose a way to bootstrap each of the possible fields individually when using the 2nd option (as an argument or a function, I kinda lean towards a function) I think that'd work API wise.

**Comment by acconrad** [comment]
@BlakeWilliams so I looked into the call and the problem is that the `init` function is never called in your library. It's only called via `websocket_client` the Erlang library, so there is no way for me to force in that argument (or alternative function).

Here is what I would recommend: we push this up right now so we can fix everyone's issue and bump the version so `0.16` -> `0.17`. At the next version `0.2` (or `1.0`, whatever the next breaking bump) you just need to change the README to state that the `slack` state no longer returns everything that it originally did and probably include a conversion guide (happy to provide that for you).

**Comment by BlakeWilliams** [comment]
@acconrad That sounds like a solid plan. I'm in favor of shipping with the extra HTTP calls now then removing them later as a breaking change (+ appropriate version bump).

**Comment by BlakeWilliams** [comment]
@acconrad I'd also really like to see a deprecation warning letting folks know that a future release will no longer auto-populate those fields with a link to the migration guide once we get that in. I think that'd be good UX for folks using the package.

**Comment by acconrad** [comment]
@BlakeWilliams all set! I also fixed the tests, added the deprecation and bumped it by 1 minor version and provided the appropriate documentation

File: lib/slack/bot.ex [hunk 2]
```diff
@@ -87,11 +105,11 @@ defmodule Slack.Bot do
       token: token,
       me: rtm.self,
       team: rtm.team,
-      bots: rtm_list_to_map(rtm.bots),
-      channels: rtm_list_to_map(rtm.channels),
-      groups: rtm_list_to_map(rtm.groups),
-      users: rtm_list_to_map(rtm.users),
-      ims: rtm_list_to_map(rtm.ims)
+      bots: bot_to_map(Bots.info(%{token: token}) |> Map.get("bot")),
+      channels: rtm_list_to_map(Channels.list(%{token: token}) |> Map.get("channels")),
```
Comment (chulkilee) [inline lib/slack/bot.ex]: `rtm_list_to_map/1` is a private func only used here, so I think it's better to change the func to simplify this code

```elixir
# before
rtm_list_to_map(Channels.list(%{token: token}) |> Map.get("channels")),

# after
web_api_to_rtm(token, &Channels.list/1, "channels")
```
```

Note that now we know we want specific key, we don't need to build the full map from the response.

File: lib/slack/bot.ex [hunk 3]
```diff
@@ -87,11 +105,11 @@ defmodule Slack.Bot do
       token: token,
       me: rtm.self,
       team: rtm.team,
-      bots: rtm_list_to_map(rtm.bots),
-      channels: rtm_list_to_map(rtm.channels),
-      groups: rtm_list_to_map(rtm.groups),
-      users: rtm_list_to_map(rtm.users),
-      ims: rtm_list_to_map(rtm.ims)
+      bots: bot_to_map(Bots.info(%{token: token}) |> Map.get("bot")),
```
Comment (chulkilee) [inline lib/slack/bot.ex]: This seems incorrect - `bot_to_map/1` wraps the response as a map with a key using`bot.id` - so there won't be any value under `"bot"`.

Comment (acconrad) [reply lib/slack/bot.ex]: it's meant to map to the original functionality as you can see from the test

Comment (chulkilee) [reply lib/slack/bot.ex]: I see the intention, but it's broken.

Previously, `rtm.bots` seem to a list of map having `"id"` key, so using `rtm_list_to_map/1`, it returns a map with key of bot ids.

Now, `bot_to_map/1` does that - so applying `Map.get("bot")` would result in `nil`

File: test/bot_test.exs [hunk 4]
```diff
@@ -8,32 +10,35 @@ defmodule Slack.BotTest do
...
-
-    assert bot_handler == Bot
-    assert slack.me.name == "fake"
-    assert slack.team.name == "Foo"
-    assert slack.bots == %{"123" => %{id: "123"}}
-    assert slack.channels == %{"123" => %{id: "123"}}
-    assert slack.groups == %{"123" => %{id: "123"}}
-    assert slack.users == %{"123" => %{id: "123"}}
-    assert slack.ims == %{"123" => %{id: "123"}}
+    with_mocks([
```
Comment (BlakeWilliams) [inline test/bot_test.exs]: I've kept it as somewhat of a personal goal to keep `mock` out of the project. I'm happy to take it on myself, but it'd be great to see the fake http client return these instead of mocking.

File: lib/slack/bot.ex (hunk 3 above)
Comment (acconrad) [reply lib/slack/bot.ex]: @chulkilee the [response](https://api.slack.com/methods/bots.info) returns a map within a map - so in order to get the `bot` property I need to go 1 layer deeper.

File: test/bot_test.exs (hunk 4 above)
Comment (acconrad) [reply test/bot_test.exs]: I tried for a few hours on Saturday and this was the only way I could think of to mock out the external Web calls

File: lib/slack/bot.ex (hunk 3 above)
Comment (chulkilee) [reply lib/slack/bot.ex]: Then shouldn't you do this?

```elixir
Bots.info(%{token: token}) |> Map.get("bot")
```

Please note that `bot_to_map/1` *wraps* the map.

```elixir
  defp bot_to_map(bot) do
    %{"#{bot.id}" => bot}
  end
```

Comment (acconrad) [reply lib/slack/bot.ex]: I'm not really understanding your question - that is what I'm doing. What are you suggesting I do differently?

Comment (chulkilee) [reply lib/slack/bot.ex]: What the current code is doing is:

```
Bots.info(%{token: token} |> bot_to_map() |> Map.get("bot"))
```

not

```
Bots.info(%{token: token} |> Map.get("bot"))
```

File: lib/slack/bot.ex (hunk 2 above)
Comment (acconrad) [reply lib/slack/bot.ex]: Feel free to update my PR and change this but I don't think this is simpler or easier to read.

File: lib/slack/bot.ex (hunk 3 above)
Comment (acconrad) [reply lib/slack/bot.ex]: The code you presented causes the tests to fail. I don't think these refactoring changes are worth it if they aren't going to keep the code working properly.

**Comment by acconrad** [comment]
@BlakeWilliams ready to merge when you are

File: lib/slack/bot.ex (hunk 3 above)
Comment (chulkilee) [reply lib/slack/bot.ex]: Mine was "suggestion", not working code. I hope you get the idea.

**Comment by acconrad** [comment]
@BlakeWilliams just checking in - fixed conflicts, ready when you are

File: lib/slack/web/docs/bots.info.json [hunk 5]
```diff
@@ -0,0 +1,15 @@
+{
+  "desc": "Gets information about a bot user.",
+  "args": {
+    "token": {
```
Comment (Slotos) [inline lib/slack/web/docs/bots.info.json]: No other doc file lists token. Listing it results in the following error:

```
    (hackney) .../deps/hackney/src/hackney_bstr.erl:35: :hackney_bstr.to_binary/1
    (hackney) .../deps/hackney/src/hackney_url.erl:313: :hackney_url.urlencode/2
    (hackney) .../deps/hackney/src/hackney_url.erl:373: :hackney_url.qs/3
    (hackney) .../deps/hackney/src/hackney_request.erl:312: :hackney_request.encode_form/1
    (hackney) .../deps/hackney/src/hackney_request.erl:320: :hackney_request.handle_body/4
    (hackney) .../deps/hackney/src/hackney_request.erl:83: :hackney_request.perform/2
    (hackney) .../deps/hackney/src/hackney.erl:373: :hackney.send_request/2
    (httpoison) lib/httpoison/base.ex:787: HTTPoison.Base.request/6
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (slack) lib/slack/web/default_client.ex:23: Slack.Web.DefaultClient.post!/2
```

File: lib/slack/bot.ex (hunk 3 above)
Comment (Slotos) [inline lib/slack/bot.ex]: Currently `bots.info` returns an empty `{ok: true}` response if `bot` argument is absent. As a result, `bot_to_map` fails.

File: lib/slack/bot.ex [hunk 6]
```diff
@@ -87,11 +105,11 @@ defmodule Slack.Bot do
...
+      channels: rtm_list_to_map(Channels.list(%{token: token}) |> Map.get("channels")),
+      groups: rtm_list_to_map(Groups.list(%{token: token}) |> Map.get("groups")),
+      users: rtm_list_to_map(Users.list(%{token: token}) |> Map.get("members")),
+      ims: rtm_list_to_map(Im.list(%{token: token}) |> Map.get("ims"))
```
Comment (Slotos) [inline lib/slack/bot.ex]: All these lists are likely partial responses. It's better to not include this info at all instead of trying to preserve a semblance of backwards compatibility. Especially considering that old `rtm.start` is truncating members lists to 500 records for almost a year already.

File: test/bot_test.exs [hunk 7]
```diff
@@ -8,32 +10,35 @@ defmodule Slack.BotTest do
   @rtm %{
```
Comment (Slotos) [inline test/bot_test.exs]: It's best to use a fake test web server here and instead of mocks later on. It's relatively safe to assume that unless Slack API misbehaves, the data will arrive as a well formed JSON. The tests will then catch issues with assuming keys to atoms conversion and others.

Mocking results of processing outside data leads to green tests that are likely to lie.

File: lib/slack/bot.ex [hunk 8]
```diff
@@ -176,6 +194,10 @@ defmodule Slack.Bot do
 
   def websocket_handle(_, _conn, state), do: {:ok, state}
 
+  defp bot_to_map(bot) do
+    %{"#{bot.id}" => bot}
```
[the remark this answers is not in the document]
Comment (acconrad) [reply lib/slack/bot.ex]: The tests pass for my original code and fail for your suggestion. Using what I think you want to use, `Map.get(bot, "id")` will result in `nil => %{id: "123"}` for the tests instead of the appropriate `"123" => %{id: "123"}` - what version of Elixir are you using? If you're on the supported version these tests should pass for you

File: lib/slack/bot.ex (hunk 6 above)
Comment (acconrad) [reply lib/slack/bot.ex]: > All these lists are likely partial responses.

So if it's at parity with `rtm.start` then are we losing any more functionality than we already had?

File: lib/slack/bot.ex (hunk 3 above)
Comment (acconrad) [reply lib/slack/bot.ex]: Is this a permissions problem because `Bots.info` requires you have the `bot` permission enabled for your app?

**Comment by acconrad** [comment]
> If possible, please revert rtm.start commit and release a minor version bump

@Slotos after reading all of these comments I'm just going to close this PR and re-open it with a major version bump since it has breaking changes. I don't want to be the one who is releasing the actual V1 of this but I think it's necessary to expose the gravity of the upgrade required. Revert PR incoming.

File: lib/slack/bot.ex (hunk 3 above)
Comment (Slotos) [reply lib/slack/bot.ex]: I was testing with a bot token on an app that doesn't have access to this scope via generic one, just in case. It could be a temporary API bug, but I don't have good way to check for that.

File: lib/slack/bot.ex (hunk 8 above)
[the remark this answers is not in the document]
Comment (Slotos) [reply lib/slack/bot.ex]: Tests are passing, it's use against real API that's failing. #114 describes the reason for it.

Basically, RTM and Bot modules decode JSON with `keys: :atoms` option. Whereas [Slack.Web.DefaultClient](https://github.com/BlakeWilliams/Elixir-Slack/blob/2a3739d13fe1ff41ae8a03356efaa7e61e4778ca/lib/slack/web/default_client.ex#L25) doesn't.

Generally speaking, it might be a good idea to get rid of keys to atoms conversion as a part of major version release.

[the remark this answers is not in the document]
Comment (BlakeWilliams) [reply lib/slack/bot.ex]: > Generally speaking, it might be a good idea to get rid of keys to atoms conversion as a part of major version release.

Agreed, that was a design decision made before the library was a library and it kinda snuck in. That'd be a great issue if there isn't one already.

**Comment by BlakeWilliams** [comment]
@acconrad Thanks a ton for all your work on this. I definitely think this is the way to go but I agree the path forward is a major release. 👍

File: lib/slack/bot.ex (hunk 6 above)
Comment (Slotos) [reply lib/slack/bot.ex]: Good point. I would still make it optional personally. The data in these keys is definitely not immutable on Slack side and it's best to fetch, cache, and expire it as specific bot requires.

**Comment by Slotos** [comment]
@acconrad thank you. I've left some responses in threads to share more info, I hope it comes in handy.

**Comment by acconrad** [comment]
@Slotos @BlakeWilliams @chulkilee 

OKAY!

This should go in after #190 - first, we add in #190 to fix everyone's problems with `rtm.connect`. _Then_ we introduce this fix to properly deprecate the Slack API while also providing a deprecation guide on how to upgrade and maintain current functionality (if you so desire all of those lists).

All tests are passing, there is no longer a dependency on the `mock` library since those tests are no longer necessary, and the code is just simpler overall.

Let me know what you think!

**Comment by acconrad** [comment]
#190 just went in so I'll fix the conflicts tonight and this can be RTM

**Comment by acconrad** [comment]
@BlakeWilliams alright conflicts resolved - this should be good to go!

File: README.md [hunk 9]
```diff
@@ -24,10 +24,27 @@ def application do
...
+## Upgrading from 0.x to 1.0
+
+The newest version of the Slack client introduces breaking changes with regards to starting and connecting to the Real Time Messaging API. `rtm.start` is now [deprecated](https://api.slack.com/methods/rtm.start) and has since been replaced with [`rtm.connect`](https://api.slack.com/methods/rtm.connect). **This has removed the list of  `bots`, `channels`, `groups`, `users`, and `ims` that are normally returned from `rtm.start`**. Additionally, these lists are now rate-limited. In order to achieve relative parity to the old way of doing things, you'll need to make one change in your code:
+
+### Make additional calls to the Slack API fo grab bots, channels, groups, users, and IMs
+
+Wherever you grab the passed in `slack` state, add in additional calls to populate these lists:
+
+```elixir
+slack
```
Comment (Slotos) [inline README.md]: `websocket_handle` in `Slack.Bot` is calling `Slack.State.update_slack`, which attempts to keep these maps up to date.

This creates a race condition where an update might arrive before the maps are created resulting in:
```
[error] ** Websocket client Slack.Bot terminating in :websocket_handle/3
   for the reason :error:{:badmap, nil}
```

Either the autoupdate routines should be purged or the system needs to be initialized with empty maps in place.

Comment (acconrad) [reply README.md]: oh good point, I would recommend purging them since those maps are no longer needed. Will save connections and also improve performance.

Comment (BlakeWilliams) [reply README.md]: Sorry if this was already discussed, but why wouldn't we grab this data for the user? Having to manually manage these maps isn't a great experience imo.

Comment (Slotos) [reply README.md]: Agreed. Existing code can be transformed into a battle tested example documentation.

I'll work on a cherry-pickable commit for this in a few hours.

Comment (Slotos) [reply README.md]: @BlakeWilliams We can do that, but IMO it shouldn't be done in a structure that gets passed around. What do you think about an agent or ETS backed store with common access interface?

Comment (Slotos) [reply README.md]: @acconrad please take a look at Slotos/Elixir-Slack@703bf400dae12effc4c9f1e6f92439a90b9dee6c

It introduces non-nil defaults to `Slack.State` and updates update routines to not fail when they encounter those. Tests pass, although I would (and will try to) spend more time to increase test coverage, as some cases aren't covered properly. There's likely to be a better way to handle some of the updates, but being an Elixir newbie I'm likely to be blind to them.

Next step is to remove updates handling from `Slack.Bot` and transform them into documentation examples for `handle_` callbacks in specific bots.

@BlakeWilliams There is an axolotl-sized dragon lying in `Slack.State` structure. While the data is being fetched an update can arrive with fresher state, which will then be promptly overridden by fetched bulk-update with older data. Slack records and events carry timestamps to indicate freshness of the data, but it's getting lost. In larger organizations this is a likely race condition with potentially visible, if not too significant, outcomes. Still, I'd personally leave implementation of a properly synchronized storage to whoever writes the bot, at least for the 1.0.0 release.

**Comment by acconrad** [comment]
@BlakeWilliams all conflicts resolved - can we get this merged in?

File: README.md [hunk 10]
```diff
@@ -24,10 +24,27 @@ def application do
 end
 
 def deps do
-  [{:slack, "~> 0.19.0"}]
+  [{:slack, "~> 1.0.0"}]
```
Comment (BlakeWilliams) [inline README.md]: This change is implying that this will bring the library to a stable `1.0.0` which I don't think is the case. Can we remove the version number bumps so I can do that in another PR?

File: README.md [hunk 11]
```diff
@@ -24,10 +24,27 @@ def application do
...
 end
 ```
 
+## Upgrading from 0.x to 1.0
+
+The newest version of the Slack client introduces breaking changes with regards to starting and connecting to the Real Time Messaging API. `rtm.start` is now [deprecated](https://api.slack.com/methods/rtm.start) and has since been replaced with [`rtm.connect`](https://api.slack.com/methods/rtm.connect). **This has removed the list of  `bots`, `channels`, `groups`, `users`, and `ims` that are normally returned from `rtm.start`**. Additionally, these lists are now rate-limited. In order to achieve relative parity to the old way of doing things, you'll need to make one change in your code:
+
+### Make additional calls to the Slack API fo grab bots, channels, groups, users, and IMs
```
Comment (BlakeWilliams) [inline README.md]:
```suggestion
### Make additional calls to the Slack API to fetch bots, channels, groups, users, and IMs
```

File: README.md (hunk 9 above)
Comment (BlakeWilliams) [reply README.md]: > Still, I'd personally leave implementation of a properly synchronized storage to whoever writes the bot, at least for the 1.0.0 release.

I feel like maintaining the state is a fundamental part of the library. It lets the folks writing bots worry about real issues instead of the plumbing to keep things up-to-date. It also feels like something that will be re-invented many times over if not implemented.

I wouldn't be opposed to it being optional, if anyone has any compelling use cases.

Comment (BlakeWilliams) [reply README.md]: > @BlakeWilliams There is an axolotl-sized dragon lying in Slack.State structure. While the data is being fetched an update can arrive with fresher state, which will then be promptly overridden by fetched bulk-update with older data.

I think that's a good point. It doesn't seem like a *huge* issue, but I definitely think it should be solved before we `1.0` the library. One thought would be that before we connect, we fetch the data to bootstrap the state before connecting.

File: README.md (hunk 10 above)
Comment (acconrad) [reply README.md]: How should we bump to signify this is breaking change though? Based on semantic versioning, a major release is one that isn't compatible with a prior release. This is a big enough change that it isn't compatible with the existing system.

**Comment by acconrad** [comment]
@BlakeWilliams all merge conflicts resolved and all tests passed - version bumped down to `0.20` can we get this merged?

File: README.md (hunk 10 above)
Comment (BlakeWilliams) [reply README.md]: Usually pre-1.0 releases aren't considered to have a stable API so it's generally okay to make breaking changes before we hit 1.0. Semver does bring that up [here](https://semver.org/#spec-item-4).

Going to 1.0 is a commitment, so I just want to make sure the library is okay with sticking to that API for a while. My big hesitance for not going 1.0 is the web API, since it needs some attention.

Comment (BlakeWilliams) [reply README.md]: Can you update this to `0.20.0` as well? Once that's updated, happy to merge this. :)

Comment (acconrad) [reply README.md]: @BlakeWilliams all set!

**Comment by BlakeWilliams** [comment]
Thanks!
